name: Create App Docker Images

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    strategy:
      matrix:
        network: [mainnet, ghostnet]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push mainnet
        if: ${{ matrix.network == 'mainnet' }}
        id: docker_build_tzvotes_mainnet
        uses: docker/build-push-action@v3
        with:
          file: ./app/Dockerfile
          context: ./app/
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Only push if on main branch
          push: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
          tags: |
            ghcr.io/marigold-dev/tzvote:latest
            ghcr.io/marigold-dev/tzvote-${{ matrix.network }}:latest
            ghcr.io/marigold-dev/tzvote-${{ matrix.network }}:${{ github.sha }}

      - name: Build and push testnet
        if: ${{ matrix.network != 'mainnet' }}
        id: docker_build_tzvotes_testnet
        uses: docker/build-push-action@v3
        with:
          file: ./app/Dockerfile.${{ matrix.network }}
          context: ./app/
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Only push if on main branch
          push: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
          tags: |
            ghcr.io/marigold-dev/tzvote-${{ matrix.network }}:latest
            ghcr.io/marigold-dev/tzvote-${{ matrix.network }}:${{ github.sha }}
