name: Create App Docker Images

on:
  push:
    branches:
      - "main"
      - "ghostnet"
    paths:
      - "app/**"

jobs:
  ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - name: Set outputs
        id: vars
        run: |
          echo "date=$(date +%Y-%m-%dT%H-%M-%S)" >> "${GITHUB_OUTPUT}"
          echo "sha_short=$(git rev-parse --short HEAD)" >> "${GITHUB_OUTPUT}"
          echo "branch=${GITHUB_REF#refs/heads/}" >> "${GITHUB_OUTPUT}"

      - uses: actions/checkout@v3.0.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: echo "{}" > esy.json
      - run: npm ci

      - name: Build
        uses: docker/build-push-action@v4
        with:
          file: ./app/Dockerfile.${{ steps.vars.outputs.branch  }}
          context: .
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: UI build and push version
        uses: docker/build-push-action@v4
        with:
          file: ./app/Dockerfile.${{ steps.vars.outputs.branch  }}
          context: .
          push: true
          tags: |
            ghcr.io/marigold-dev/tzvote-:${{ steps.vars.outputs.date }}-${{ steps.vars.outputs.sha_short }}-${{ steps.vars.outputs.branch  }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
