name: Create App Docker Images

on:
  push:
    branches:
      - "main"
    paths:
      - "app/**"
  workflow_dispatch:

jobs:
  docker:
    strategy:
      matrix:
        network: [mainnet, ghostnet]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - name: Set outputs
        id: vars
        run: |
          echo "date=$(date +%Y-%m-%dT%H-%M-%S)" >> "${GITHUB_OUTPUT}"
          echo "sha_short=$(git rev-parse --short HEAD)" >> "${GITHUB_OUTPUT}"
          echo "branch=${GITHUB_REF#refs/heads/}" >> "${GITHUB_OUTPUT}"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push mainnet
        if: ${{ matrix.network == 'mainnet' }}
        id: docker_build_tzvotes_mainnet
        uses: docker/build-push-action@v3
        with:
          file: ./app/Dockerfile
          context: ./app/
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Only push if on main branch
          push: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/mainnet' }}
          tags: |
            ghcr.io/marigold-dev/tzvote:${{ steps.vars.outputs.date }}-${{ steps.vars.outputs.sha_short }}-${{ matrix.network }}

      - name: Build and push testnet
        if: ${{ matrix.network != 'mainnet' }}
        id: docker_build_tzvotes_testnet
        uses: docker/build-push-action@v3
        with:
          file: ./app/Dockerfile.${{ matrix.network }}
          context: ./app/
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Only push if on main branch
          push: ${{ github.ref == 'refs/heads/ghostnet' }}
          tags: |
            ghcr.io/marigold-dev/tzvote:${{ steps.vars.outputs.date }}-${{ steps.vars.outputs.sha_short }}-${{ matrix.network }}

