name: Create App Docker Image for Testnets

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    strategy:
      matrix:
        network: [ithacanet]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build_delegator-votes
        uses: docker/build-push-action@v2
        with:
          file: ./app/Dockerfile.${{ matrix.network }}
          context: ./app/
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Only push if on main branch
          push: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
          tags: |
            ghcr.io/marigold-dev/delegator-votes-${{ matrix.network }}:latest
            ghcr.io/marigold-dev/delegator-votes-${{ matrix.network }}:${{ github.sha }}
